# Generated by Django 3.0.4 on 2020-09-25 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('major_version', models.CharField(max_length=10)),
                ('minor_version', models.IntegerField()),
                ('publish_time', models.DateTimeField()),
                ('expiration_time', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('team', models.CharField(max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ds_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'major_version', 'minor_version')},
            },
        ),
        migrations.CreateModel(
            name='DatasetInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('publish_time', models.DateTimeField()),
                ('data_time', models.DateTimeField()),
                ('deleted_time', models.DateTimeField(null=True)),
                ('revision', models.IntegerField()),
                ('row_count', models.BigIntegerField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Dataset')),
                ('parent_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.DatasetInstance')),
            ],
            options={
                'unique_together': {('dataset', 'path', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='DataLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=1024)),
                ('offset', models.IntegerField()),
                ('size', models.BigIntegerField(null=True)),
                ('dataset_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='main.DatasetInstance')),
            ],
        ),
    ]
